/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrianaGroupRouteImport } from './routes/oriana-group'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WeddingFilmsRouteImport } from './routes/wedding-films'
import { Route as WeddingPhotographyRouteImport } from './routes/wedding-photography'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioRealWeddingsSlugRouteImport } from './routes/portfolio.real-weddings.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrianaGroupRoute = OrianaGroupRouteImport.update({
  id: '/oriana-group',
  path: '/oriana-group',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingFilmsRoute = WeddingFilmsRouteImport.update({
  id: '/wedding-films',
  path: '/wedding-films',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPhotographyRoute = WeddingPhotographyRouteImport.update({
  id: '/wedding-photography',
  path: '/wedding-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioRealWeddingsSlugRoute =
  PortfolioRealWeddingsSlugRouteImport.update({
    id: '/real-weddings/$slug',
    path: '/real-weddings/$slug',
    getParentRoute: () => PortfolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/oriana-group': typeof OrianaGroupRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-films': typeof WeddingFilmsRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/real-weddings/$slug': typeof PortfolioRealWeddingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/oriana-group': typeof OrianaGroupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-films': typeof WeddingFilmsRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/portfolio/real-weddings/$slug': typeof PortfolioRealWeddingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/oriana-group': typeof OrianaGroupRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-films': typeof WeddingFilmsRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/real-weddings/$slug': typeof PortfolioRealWeddingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/oriana-group'
    | '/portfolio'
    | '/sitemap.xml'
    | '/wedding-films'
    | '/wedding-photography'
    | '/portfolio/'
    | '/portfolio/real-weddings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/oriana-group'
    | '/sitemap.xml'
    | '/wedding-films'
    | '/wedding-photography'
    | '/portfolio'
    | '/portfolio/real-weddings/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/oriana-group'
    | '/portfolio'
    | '/sitemap.xml'
    | '/wedding-films'
    | '/wedding-photography'
    | '/portfolio/'
    | '/portfolio/real-weddings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OrianaGroupRoute: typeof OrianaGroupRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingFilmsRoute: typeof WeddingFilmsRoute
  WeddingPhotographyRoute: typeof WeddingPhotographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oriana-group': {
      id: '/oriana-group'
      path: '/oriana-group'
      fullPath: '/oriana-group'
      preLoaderRoute: typeof OrianaGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-films': {
      id: '/wedding-films'
      path: '/wedding-films'
      fullPath: '/wedding-films'
      preLoaderRoute: typeof WeddingFilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-photography': {
      id: '/wedding-photography'
      path: '/wedding-photography'
      fullPath: '/wedding-photography'
      preLoaderRoute: typeof WeddingPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/real-weddings/$slug': {
      id: '/portfolio/real-weddings/$slug'
      path: '/real-weddings/$slug'
      fullPath: '/portfolio/real-weddings/$slug'
      preLoaderRoute: typeof PortfolioRealWeddingsSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PortfolioRealWeddingsSlugRoute: typeof PortfolioRealWeddingsSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIndexRoute: PortfolioIndexRoute,
  PortfolioRealWeddingsSlugRoute: PortfolioRealWeddingsSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OrianaGroupRoute: OrianaGroupRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingFilmsRoute: WeddingFilmsRoute,
  WeddingPhotographyRoute: WeddingPhotographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
