/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WeddingFilmsRouteImport } from './routes/wedding-films'
import { Route as WeddingPhotographyRouteImport } from './routes/wedding-photography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingFilmsRoute = WeddingFilmsRouteImport.update({
  id: '/wedding-films',
  path: '/wedding-films',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPhotographyRoute = WeddingPhotographyRouteImport.update({
  id: '/wedding-photography',
  path: '/wedding-photography',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/wedding-films': typeof WeddingFilmsRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/wedding-films': typeof WeddingFilmsRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/wedding-films': typeof WeddingFilmsRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/wedding-films' | '/wedding-photography'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/wedding-films' | '/wedding-photography'
  id: '__root__' | '/' | '/about' | '/wedding-films' | '/wedding-photography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WeddingFilmsRoute: typeof WeddingFilmsRoute
  WeddingPhotographyRoute: typeof WeddingPhotographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-films': {
      id: '/wedding-films'
      path: '/wedding-films'
      fullPath: '/wedding-films'
      preLoaderRoute: typeof WeddingFilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-photography': {
      id: '/wedding-photography'
      path: '/wedding-photography'
      fullPath: '/wedding-photography'
      preLoaderRoute: typeof WeddingPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WeddingFilmsRoute: WeddingFilmsRoute,
  WeddingPhotographyRoute: WeddingPhotographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
